#
# Programmer:    Craig Stuart Sapp <craig@ccrma.stanford.edu>
# Creation Date: Wed Mar 16 13:09:12 PDT 2016
# Last Modified: Wed Mar 16 13:09:16 PDT 2016
# Filename:      collatemd2
# Syntax:        perl 5
#
# Description:   Creates footer files for specifying the page footers in
#                final PDF files.
#

MAKEFOOTER = ../../bin/makefooter

all:
	$(MAKEFOOTER) info.txt

