#
# Programmer:    Craig Stuart Sapp <craig@ccrma.stanford.edu>
# Creation Date: Wed Mar 16 13:14:01 PDT 2016
# Last Modified: Wed Mar 16 13:14:06 PDT 2016
# Filename:      pdf-score/Makefile
# Syntax:        perl 5
#
# Description:   Creates PDF files for full scores.
#

MAKEPDFS   = ../../bin/makepdfs

all: movements works opus

movements:
	$(MAKEPDFS) ../pages-score/*.pag

works:
	@echo "Creating PDF for each work"

opus:
	@echo "Creating PDF for entire opus"


